server:
  port: 8761
eureka:
  instance:
    hostname: localhost
    lease-renewal-interval-in-seconds: 1
    lease-expiration-duration-in-seconds: 2
  client:
    #    配置当前eureka为server
    registerWithEureka: false
    fetchRegistry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    waitTimeInMsWhenSyncEmpty: 0
    #    关闭eureka保护措施 上线开启
    enable-self-preservation: false
    # 清理无效节点时间间隔（单位毫秒，默认是60*1000）
    eviction-interval-timer-in-ms: 3000
spring:
  application:
    name: eureka_server

