eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 9001
spring:
  application:
    name: service-feign
  cloud:
    loadbalancer:
      retry:
        enabled: true
feign:
  hystrix:
    enabled:  true
#spring.cloud.loadbalancer.retry.enabled=true
